# see https://docs.docker.com/compose/compose-file/compose-versioning/
version: "3.5" # specify docker-compose version, v3.5 is compatible with docker 17.12.0+
services:
  timemanager:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    restart: always
    environment:
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: time_manager
      POSTGRES_USER: postgres